use_frameworks!

target 'MDPageControl_Example' do
  pod 'MDPageControl', :path => '../'

  target 'MDPageControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
